<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\eBackup.Core\eBackup.Core.csproj" />
    <ProjectReference Include="..\eBackup.Security\eBackup.Security.csproj" />
    <ProjectReference Include="..\eBackup.Storage.Local\eBackup.Storage.Local.csproj" />
    <ProjectReference Include="..\eBackup.Storage.Sftp\eBackup.Storage.Sftp.csproj" />
    <ProjectReference Include="..\eBackup.Modules.Obs\eBackup.Modules.Obs.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Windows-only: использует DPAPI через eBackup.Security -->
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
